# This is a basic workflow to help you get started with Actions

name: Pull Request

# Triggers on pull requests
on:
  pull_request:
    branches: [ $default-branch, 'ollewis-dest' ]

jobs:
  # PR Job
  pr_check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      # Checks-out the repo under $GITHUB_WORKSPACE, so our job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # NPM Install
      - name: Run npm install    
        run: npm install

      # Lint Check
      - name: Run the lint check
        run: npm run lint
      
      # Format/Prettier Check
      - name: Run the formatting check
        run: npm run format-check

      # Build Check
      - name: Run npm checks
        run: echo BUILDCHECK

      # Commit changes made by the lint and format check.
      - name: Git Auto Commit - Format and Lint Changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2

