# This is a basic workflow to help you get started with Actions

name: Pull Request

# Triggers on pull requests
on:
  pull_request:
    branches: [$default-branch, 'ollewis-dest' ]

jobs:
  # PR Job
  pr_check:
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repo under $GITHUB_WORKSPACE, so our job can access it
      - uses: actions/checkout@v2
      
      # Test
      - name: PR test step
        run: |
          echo Start
          echo End
      
      # Lint Check
      - name: Run the lint check
        run: echo LINTER
      
      # Format/Prettier Check
      - name: Run the formatting check
        run: echo FORMATTING

      # Build Check
      - name: Run npm checks
        run: echo BUILDING
