name: vikelabs-push

on:
  push:
    branches: [robert]

jobs:
  build: ubuntu-latest
  steps:
    # Checks-out the repo under $GITHUB_WORKSPACE, so our job can access it
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run build
      run: |
        npm install
        npm run build
